1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.

In [1]:
import numpy as np

### 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. Create a vector with values ranging from 10 to 49

In [4]:
x1=np.arange(10,49)
print(x1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


### 3. Create a 3x3 matrix with values ranging from 0 to 8


In [6]:
x2=np.arange(0,8).reshape(2,2,2)
print(x2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [32]:
x3=np.array([1,2,0,0,4])

print(x3.nonzero())

(array([0, 1, 4], dtype=int64),)


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [38]:
x4=np.random.random(size=(10,10))
print("Minimum value : ",x4.min())
print("Maxmum value : ",x4.max())

Minimum value :  0.001561544677642912
Maxmum value :  0.9874937629427898


### 6. Create a random vector of size 30 and find the mean value.

In [43]:
x5=np.random.random(size=30)
print("Mean value : ",x5.mean())

Mean value :  0.5099933277860537
